CREATE TABLE IF NOT EXISTS `leave` (
    `id` BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '留言 id',
    `username` VARCHAR(255) NOT NULL COMMENT '留言者',
    `email` VARCHAR(255) NOT NULL COMMENT '留言者的 mail',
    `content` TEXT NOT NULL COMMENT '評論內容',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '發佈時間',
    `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新時間'
) CHARSET `utf8mb4`;
